// flow-typed signature: 77d66aa5a8ef4f9ea9776962206a2546
// flow-typed version: <<STUB>>/@tracoco/react-cms-helpers_v0.0.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tracoco/react-cms-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tracoco/react-cms-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tracoco/react-cms-helpers/lib/cancelButton' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/confirmButton' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/context' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/createEmptyData' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/index' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/item' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/liteCMS' {
  declare module.exports: any;
}

declare module '@tracoco/react-cms-helpers/lib/transformData' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tracoco/react-cms-helpers/lib/cancelButton.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/cancelButton'>;
}
declare module '@tracoco/react-cms-helpers/lib/confirmButton.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/confirmButton'>;
}
declare module '@tracoco/react-cms-helpers/lib/context.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/context'>;
}
declare module '@tracoco/react-cms-helpers/lib/createEmptyData.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/createEmptyData'>;
}
declare module '@tracoco/react-cms-helpers/lib/index.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/index'>;
}
declare module '@tracoco/react-cms-helpers/lib/item.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/item'>;
}
declare module '@tracoco/react-cms-helpers/lib/liteCMS.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/liteCMS'>;
}
declare module '@tracoco/react-cms-helpers/lib/transformData.js' {
  declare module.exports: $Exports<'@tracoco/react-cms-helpers/lib/transformData'>;
}
